### ISSUE TITLE
Name database doesn't work

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#58]
Clicking "Tools->Name database" gives me nothing but an error message on the terminal:

```
Traceback (most recent call last):
  File "/home/jano/Projekte/trelby/src/trelby.py", line 2501, in OnNameDatabase
    dlg = namesdlg.NamesDlg(self, self.panel.ctrl)
  File "/home/jano/Projekte/trelby/src/namesdlg.py", line 125, in __init__
    vsizer.Add(hsizer2, 0, wx.EXPAND | wx.ALIGN_CENTER)
wx._core.wxAssertionError: C++ assertion "CheckSizerFlags(!((flags) & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)))" failed at /tmp/pip-install-k2tr_1ur/wxpython_20a905876d21425d9ddbd4366251e8e5/ext/wxWidgets/src/common/sizer.cpp(2288) in DoInsert(): wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL will be ignored in this sizer: wxEXPAND overrides alignment flags in box sizers
```

I think it is just broken.

**Comment by limburgher** [comment]
This works for me, what wxPython4 do you have? Mine is 4.2.0.

**Comment by jonafato** [comment]
This was fixed in https://github.com/limburgher/trelby/pull/55.
